### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by FoxIshDaBest** [Ultra-DEV/4TifyAPI#1]
I opened this in Netbeans, and lots of errors happened. We are working on fixing these.

**Comment by Ultra-DEV** [comment]
I'll get on to it.

I'll close the issue when done.

**Comment by FoxIshDaBest** [comment]
Alright. The Command_getgamemode has no errors. You could use that as a refrence

**Comment by FoxIshDaBest** [comment]
I fixed the Util also

**Comment by Ultra-DEV** [comment]
Fixed.
